USD = "//*[@class='dynamicFilter']"
IMAGE_USD = "//*[@class='filterImage usd']"
ASSET_BCH = "//*[@data-instrumentid='1024']//img"
USD_ASSETS = "//div[@class='content']/span[@class='currencySymbol'][contains(.,'USD')]"
BCH_ASSETS = "//div[@class='content']/span[@class='currencySymbol'][contains(.,'BCH')]"
USD_OPTION_FROM_USD_DROPDOWN = "//*[@class='assetsGroupTypeFilter_exchange_usd']"
BTC_USD_INSTRUMENT = "//*[@id='dx_platform']//li[@data-instrumentid = '1013']"
DXCASH_USD_INSTRUMENT = "//*[@id='dx_platform']//li[@data-instrumentid = '1030']"
DXCASH_USD_TITLE_ON_INSTRUMENT_QUICK_INFO_PANEL = "//*[@id='exchangeEntity_0']//div[@class='assetName'][contains(.,'DXCASH/USD')]"
MARKET_TAB_SELECTED = "//*[@id='exchangeEntity_0']//div[@class='tradeType market selected']"
ESTIMATED_PRICE_FOR_BUY_MARKET ="//*[@id='exchangeEntity_0']//div[@class='tradeBtn buyButton']//div[@class = 'price']"
ESTIMATED_PRICE_FOR_SELL_MARKET = "//*[@id='exchangeEntity_0']//div[@class='tradeBtn sellButton']//div[@class = 'price']"

