from src.base import base_url

base = base_url

OPEN_ACCOUNT_FRAME = "//*[@id='platformAuthDialog']"
OPEN_ACCOUNT_BOX_ID = "openAccountDxForm"
OPEN_ACCOUNT_BOX = "//*[@id='openAccountDxForm']"
OPEN_ACCOUNT_LOGO = "//*[@class='registration hidden']/div[@class='title']"
FIRST_NAME_FIELD = "//input[@name='firstName'][@placeholder='First name']"
LAST_NAME_FIELD = "//input[@name='lastName'][@placeholder='Last name']"
EMAIL_FIELD = "//input[@name='email'][@placeholder='Email address']"
PASSWORD_FIELD = "//input[@name='password']"
CAPTCHA = "//input[@name='captcha']"  # "//div[@class='recaptcha-checkbox-checkmark'][@role='presentation']"
CAPTCHA_FRAME = "//*[@class='g-recaptcha']//iframe"
CAPTCHA_MAIN_FRAME = "//*[@class='g-recaptcha'][@data-theme='light']"
CREATE_ACCOUNT_BUTTON = "//*[@class='registration-form-wrapper']//input[@class='formButton']"   # "//input[@class='formButton'][@value='Create Account']"
NEWSLETTERS_CHECKBOX = "//div[@class='receivePromoEmail']//span[@class='checkmark']"
CERTIFY_CHECKBOX = "//div[@class='acceptTerms']//span[@class='checkmark']"
# "//*[@class='password']/div[@class='error fieldError hidden']/span"
PASSWORD_ERROR = "//*[@id='openAccountDxForm']/div[@class='password']//div[@class='error fieldError hidden']"
TERM_OF_USE_LINK = "//a[@class='termOfUse']"
PRIVACY_POLICY_LINK = "//a[@class='privacyPolicy']"
SIGNIN_LINK = "//a[@class='custom loginLink']"
# "//div[@class='email']/div[@class='error fieldError hidden']/span"
EMAIL_ERROR = "//*[@id='openAccountDxForm']/div[@class='email']//div[@class='error fieldError hidden']"

# Verify your email screen
EMAIL_NOT_ARRIVED = "//*[@class='resendBtn']"
EMAIL_ALREADY_VERIFIED = "//*[@class='reSyncBtn']"
GO_BACK_LINK = "//*[@class='emailVerification hidden']//a[@href='/']"

# Verified email screen
CONTINUE_BUTTON = "//*[@id='openAccountDxEmailVerificationForm']//button"
GO_BACK_LINK_V = "//div[@id='dxPackageContainer_openAccountDx']//div[@class='emailVerification hidden']//a[@href='{0}']".format(base)

# Add phone number screen
SELECT_COUNTRY_DROPDOWN = "//a[@class='chzn-single chzn-default']"
SELECT_COUNTRY_FIELD = "//div[@class='chzn-search']/input"
PHONE_FIELD = "//div[@class='phoneNumber']/input[@name='phone']"
PHONE_FIELD_DISABLED = "//div[@class='phoneNumber']/input[@class='formField'][@disabled='disabled']"
PHONE_PREFIX = "//div[@class='phoneNumber']/input[@name='phonePrefix']"
SEND_BUTTON = "//input[@value='Send']"
GO_BACK_LINK_P = "//*[@class='subscription']/a[@href='/']"
ADD_PHONE_MESSAGE = "//div[@class='info'][contains(text(),'This will secure your account by requiring a short code from your phone when making large transactions.')]"
FIELD_ERROR = "//*[@class='error fieldError hidden'][@style='display: block;']/span[@class='text']"
ERROR_SENDING_SMS = "//*[@id='openAccountDxAddPhoneForm']//span[contains(.,'error')]"
TOKEN_ERROR = "//*[@class='error hidden']/div[@class='text']"
CUSTOMER_EXIST_ERROR = "//div[@class='error fieldError hidden'][@style='display: block;']"

# Verify phone number screen
CODE_FIELD = "//input[@name='code']"
SUBMIT_BUTTON = "//input[@value='Submit']"
RESEND_LINK = "//*[@class='resend']"
ANOTHER_PHONE_LINK = "//*[@class='resetPhone']/a"
PHONE_CODE_TEXT = "//*[@class='upperText']"
GO_BACK_LINK_E = "//*[@class='validatePhoneNumber hidden']/div[@class='subscription']"

# Personal details screen
NEXT_BUTTON = "//*[@id='openAccountDxDetailsForm']//input[@class='formButton']"
NAME_FIELD = "//*[@name='firstName'][@placeholder='First name']"
DATE_OF_BIRTH = "//input[@class='formField hasDatepicker']"
CALENDAR_TABLE = "//table[@class='ui-datepicker-calendar']"
CALENDAR = "//*[@id='ui-datepicker-div']"
CALENDAR_ID = "ui-datepicker-div"
DATE = "//a[@class='ui-state-default'][contains(.,'')]"
MONTH_SELECT = "//select[@class='ui-datepicker-month']"
YEAR_SELECT = "//select[@class='ui-datepicker-year']"
DAY = "//td[@class=' ui-datepicker-week-end ']/a[@class='ui-state-default'][contains(.,'2')]"
CITY_FIELD = "//input[@name='city']"
ZIP_FIELD = "//input[@name='postCode']"
ADDRESS_FIELD = "//input[@name='street']"
ADDRESS_2_FIELD = "//input[@name='streetTwo']"
US_CHECKNOX = "//div[@class='uSTaxReportable']//span[@class='checkmark']"
POLITICAL_CHECKBOX = "//div[@class='politicallyExposed']//span[@class='checkmark']"
GENDER_DROPDOWN_ID = "genderPlatformSelect_0_chzn"  # "//*[@id='genderPlatformSelect_0_chzn']"
GENDER_MALE_OPTION_FROM_DROPDOWN = "//*[@id='genderPlatformSelect_0_chzn_o_1']"
COUNTRY_DROPDOWN_ID = "countryPlatformSelect_0_chzn"   # "//*[@id='countryPlatformSelect_0_chzn']"
INPUT_FIELD_FOR_COUNTRY = "//*[@id='countryPlatformSelect_0_chzn']//input[@type='text']"

# Client Checklist 1
EMPLOYMENT_DROPDOWN = "//*[@class='employmentStatusTr']//a"
EMPLOYMENT_OPTIONS = "//*[@class='employmentStatusTr']//li"
BUSINESS_NAME_INPUT = "//input[@name='businessNameEmployed']"
OCCUPATION_INPUT = "//input[@name='occupationEmployed']"
BUSINESS_YEAR_INPUT = "//input[@name='businessSetupYear']"
INDUSTRY_DROPDOWN = "//*[@class='industrySectorEmployedTr']//a[@class='chzn-single chzn-default']"
INDUSTRY_OPTIONS = "//*[@class='industrySectorEmployedTr']//li"
NEXT_BUTTON_CHECKLIST1 = "//*[@id='dxPackageContainer_openAccountDx']//li[@class = 'stepContainer hidden step_1']//td[@class = 'submitTd']/input[@class = 'submitInput']"
# NEXT_BUTTON_CHECKLIST1 = "//*[@id='dxPackageContainer_openAccountDx']//div[@class='dynamicQuestions hidden']//li[@class='stepContainer hidden step_1']//input[@class='submitInput']"

# Client Checklist 2
ANNUAL_INCOME = "//*[@class='annualIncomeTr']//a"
ANNUAL_OPTIONS = "//*[@class='annualIncomeTr']//li"
SOURCE_SELECT = "//*[@class='sourceOfDealingFundsTr']//a"
SOURCE_OPTIONS = "//*[@class='sourceOfDealingFundsTr']//li"
INHERITANCE_CHECKBOX = "//*[@for='mainActivityGeneratedWealth_65']/span[@class='checkmark']"
#NEXT_BUTTON_CHECKLIST2 = "//*[@class='stepContainer hidden step_2']//td[@class='submitTd']/input"
TAXES_DROPDOWN = "//*[@id='countryOfTaxPlatformSelect_27_chzn']/a[@class='chzn-single chzn-default'][@class]/div"
YES_OPTION = "//*[@id='countryOfTaxPlatformSelect_27']/option[@_orightml = 'Yes']"
PURPOSE_DROPDOWN = "//*[@id='main_trading_purposePlatformSelect_29_chzn']/a/div/b"
INTRADAY_TRADING_OPTION = "//*[@id='main_trading_purposePlatformSelect_18_chzn_o_1']"
NEXT_BUTTON_CHECKLIST2 = "//*[@class='stepContainer hidden step_1']//td[@class='submitTd']/input"
TITLE = "//*[@class = 'countryOfTaxTr']//div[@class = 'propName condensed']"

# Client Checklist 3
DOCUMENTS = "//div[@class='uploadText']"
DOCUMENT_1 = "//*[@class='doc_1_1_0Hidden hidden']"
DOCUMENT_2 = "//*[@class='doc_1_2_0Hidden hidden']"
DOCUMENT_3 = "//*[@class='doc_2_1_0Hidden hidden']"
NEXT_BUTTON_CHECKLIST3 = "//*[@id='openAccountUploadDocumentsForm']//input[@class='formButton']"
FINISH_BUTTON = "//div[@class='finish']/input[@type='submit']"
