SIGNIN_BOX = "//*[@class='content']"
SIGNIN_TITLE = "//*[@class='loginTitle']"
USERNAME_FIELD = "//input[@name='email']"
PASSWORD_FIELD = "//input[@name='passwordPopupFake']"
PASSWORD_FIELD_TRUE = "//input[@name='password']"
CAPTCHA = "//input[@name='captcha']"  # "//div[@class='recaptcha-checkbox-checkmark'][@role='presentation']"
CAPTCHA_FRAME = "//*[@class='g-recaptcha']//iframe"
CAPTCHA_MAIN_FRAME = "//*[@class='g-recaptcha'][@data-theme='light']"
SIGNIN_BUTTON = "//input[@class='formButton']"  # "//input[@value='Sign In']"
KEEP_ME_CHECKBOX = "//*[@class='checkmark']"
FORGOT_PASSWORD_LINK = "//*[@class='authPopupForgotPassword']"
REGISTER_LINK = "//*[@class='authPopupRegister']"
CAPTCHA_ERROR = "//*[@class='fieldError hidden captchaError']//span[@class='errorText']"
CAPTCHA_PRIVACY = "//a[@target='_blank'][contains(.,'Privacy')]"
CAPTCHA_TERMS = "//a[@target='_blank'][contains(.,'Terms')]"
SESSION_EXPIRED_TITLE = "//div[@class ='loginTitle'][contains(text(),'Session expired')]"
ACCOUNT_SETTINGS_SELECTED = "//*[@id='settingsTabs']/li[@class='dx_myAccount_navTab_accountSettings selected']"
BALANCE_SELECTED = "//li[@class = 'dx_funds_navTab_fundsBalance first selected']"
CUSTOMER_LOGGED_NAME = "//*[@class='headerBtn info']/span"
